Multiple Linear Regression?
            *2 yan zayada
            *y=b0​+b1​x1​+b2​x2​+b3​x3​ {equation}
            *Experience+Education+Age=salary{example}
            *2D not possible
            *Little bit complex{complexity}
            *Sometimes more accuracy because it consider multiple factors

Import Libraries:

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

Create Dataset:

In [2]:
data = {
    "Experience":[1,2,3,4,5,6,7,8,9,10],
    "Education":[12,12,14,14,16,16,18,18,20,20],
    "Age":[22,23,24,26,27,29,31,33,35,37],
    "Salary":[30000,35000,45000,55000,65000,75000,85000,95000,105000,115000]
}

df = pd.DataFrame(data)

print(df)

   Experience  Education  Age  Salary
0           1         12   22   30000
1           2         12   23   35000
2           3         14   24   45000
3           4         14   26   55000
4           5         16   27   65000
5           6         16   29   75000
6           7         18   31   85000
7           8         18   33   95000
8           9         20   35  105000
9          10         20   37  115000

In [3]:
df.head()

   Experience  Education  Age  Salary
0           1         12   22   30000
1           2         12   23   35000
2           3         14   24   45000
3           4         14   26   55000
4           5         16   27   65000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Experience  10 non-null     int64
 1   Education   10 non-null     int64
 2   Age         10 non-null     int64
 3   Salary      10 non-null     int64
dtypes: int64(4)
memory usage: 448.0 bytes

In [5]:
df.describe()

       Experience  Education        Age       Salary
count    10.00000  10.000000  10.000000      10.0000
mean      5.50000  16.000000  28.700000   70500.0000
std       3.02765   2.981424   5.186521   29481.6327
min       1.00000  12.000000  22.000000   30000.0000
25%       3.25000  14.000000  24.500000   47500.0000
50%       5.50000  16.000000  28.000000   70000.0000
75%       7.75000  18.000000  32.500000   92500.0000
max      10.00000  20.000000  37.000000  115000.0000

Separate X and y:

features:

In [6]:
X = df[['Experience','Education','Age']]

target:

In [7]:
y = df['Salary']

Train-Test Split:

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

Create Model:

In [9]:
model = LinearRegression()

Train Model:

In [10]:
model.fit(X_train, y_train)

LinearRegression()

Coefficients:

In [13]:
print(model.coef_)

[5643.56435644  581.68316832 2029.7029703 ]

Intercept:

In [14]:
print(model.intercept_)

-27821.782178217894

Prediction:

In [15]:
y_pred = model.predict(X_test)

Compare Actual vs Predicted:

In [16]:
comparison = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

print(comparison)

   Actual      Predicted
8  105000  105643.564356
1   35000   37128.712871

Evaluation:

In [2]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

MAE:

In [4]:
mae = mean_absolute_error(y_test, y_pred)
print(mae)

NameError: name 'y_test' is not defined

New prediction:

In [18]:
new_employee = [[8,18,30]]
prediction = model.predict(new_employee)

print("Predicted Salary:", prediction)

Predicted Salary: [88688.11881188]

c:\Users\BEST LAPTOP\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(